name: manzac_app
description: "Logistica Manzac"
publish_to: 'none'

version: 1.2.4+10

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  firebase_messaging: ^14.1.2
  firebase_core: ^2.32.0
  flutter_secure_storage: ^9.2.4
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  http: ^1.3.0
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  connectivity_plus: ^6.1.3
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.8
  bottom_navy_bar: ^6.1.0
  material_color_gen: ^2.0.0
  flutter_vector_icons: ^2.0.0
  fluttertoast: ^8.2.12
  animate_do: ^4.2.0
  modal_bottom_sheet: ^3.0.0
  adaptive_action_sheet: ^2.0.4
  auto_size_text_plus: ^3.0.2
  toggle_switch: ^2.3.0
  image: ^4.5.3
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  flutter_slidable: ^4.0.0
  uuid: ^4.5.2
  flutter_spinkit: ^5.2.1

#  flutter_launcher_icons: ^0.14.3
#  dart run flutter_launcher_icons
#  flutter_native_splash: ^2.2.15
#  dart run flutter_native_splash:create 
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_ce_generator: ^1.11.1
  build_runner: ^2.11.0

  flutter_lints: ^5.0.0
#  change_app_package_name: ^1.4.0
#  dart run change_app_package_name:main com.mtgdevs.manzaclogistic

flutter:
  uses-material-design: true

  assets:
    - assets/logo-manzac.png
    - assets/manzac-login.png
    - assets/manzac-logo-doc1.png
    - assets/manzac-logo-doc2.png
    - assets/reporte_danios_contenedores.png
    - assets/sin_firma.png